// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StepHandler is an autogenerated mock type for the StepHandler type
type StepHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *StepHandler) Execute(_a0 ...interface{}) (interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0...)
	ret := _m.Called(_ca...)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(...interface{}) interface{}); ok {
		r0 = rf(_a0...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(_a0...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleRollbackError provides a mock function with given fields:
func (_m *StepHandler) HandleRollbackError() {
	_m.Called()
}

// Rollback provides a mock function with given fields:
func (_m *StepHandler) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
