// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ClientHelper is an autogenerated mock type for the ClientHelper type
type ClientHelper struct {
	mock.Mock
}

// Post provides a mock function with given fields: url, body, headers, auth
func (_m *ClientHelper) Post(url string, body interface{}, headers http.Header, auth map[string]string) (*http.Response, error) {
	ret := _m.Called(url, body, headers, auth)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, interface{}, http.Header, map[string]string) *http.Response); ok {
		r0 = rf(url, body, headers, auth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}, http.Header, map[string]string) error); ok {
		r1 = rf(url, body, headers, auth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
